fix(text): add curly for translation
CrisisCleanup/crisiscleanup-3-web pull request #1412
Opened 2022-06-01 17:37 UTC by pablo014

2022-06-01 21:50 UTC, tabiodun requested changes

2022-06-01 21:50 UTC, tabiodun commented on src/components/phone/UpdateStatus.vue
> +              {{ $t(`~~${item.name_t}`) }}
```suggestion
              {{ $t(item.name_t) }}
```

2022-06-01 21:50 UTC, tabiodun commented on src/components/phone/UpdateStatus.vue
> +            {{ $t(`~~${section.name}`) }}
```suggestion
            {{ section.name }}
```

2022-06-01 21:52 UTC, tabiodun commented on src/components/phone/UpdateStatus.vue
> +            {{ $t(`~~${section.name}`) }}
Regular parameters do not require translation

2022-06-01 21:53 UTC, tabiodun commented on src/components/phone/ActiveCall.vue
>              >{{ $t('~~New Case') }}
```suggestion
            >{{ $t('phoneDashboard.new_case') }}
```

2022-09-22 16:53 UTC, deepanchal commented
Maybe outdated?

2022-09-22 16:53 UTC, closed without merging